# Generated by Django 5.2.3 on 2025-06-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="модель")),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="услуга")),
            ],
        ),
        migrations.CreateModel(
            name="StatusDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="статус доставки"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="тип упаковки")),
            ],
        ),
        migrations.CreateModel(
            name="NumberModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="номер")),
                (
                    "name_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.modeltransport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("travel_time", models.DateTimeField(verbose_name="время в пути")),
                ("distance", models.IntegerField(verbose_name="дистанция")),
                (
                    "mediafile",
                    models.FileField(upload_to="", verbose_name="медиа файл"),
                ),
                (
                    "technical_condition",
                    models.CharField(
                        choices=[(1, "исправно"), (0, "неисправно")],
                        verbose_name="техническое состояние",
                    ),
                ),
                (
                    "number_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.numbermodel",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.service"
                    ),
                ),
                ("stutus_delivery", models.ManyToManyField(to="api.statusdelivery")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.typepackage",
                    ),
                ),
            ],
        ),
    ]
