# Generated by Django 5.2.3 on 2025-06-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_modeltransport_service_statusdelivery_typepackage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="service",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="stutus_delivery",
        ),
        migrations.AddField(
            model_name="delivery",
            name="service",
            field=models.ManyToManyField(to="api.service"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="stutus_delivery",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.statusdelivery",
            ),
        ),
    ]
