# Generated by Django 5.2.3 on 2025-06-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_delivery_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="travel_time",
        ),
    ]
