# Generated by Django 5.2.3 on 2025-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_delivery_travel_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="travel_time",
            field=models.DurationField(default=None, verbose_name="время в пути"),
        ),
    ]
