# Generated by Django 5.2.3 on 2025-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delivery_travel_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="technical_condition",
            field=models.CharField(
                choices=[("1", "исправно"), ("0", "неисправно")],
                verbose_name="техническое состояние",
            ),
        ),
    ]
