# Generated by Django 5.2.3 on 2025-06-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_delivery_technical_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="mediafile",
            field=models.FileField(upload_to="media", verbose_name="медиа файл"),
        ),
    ]
