# Generated by Django 5.2.3 on 2025-06-14 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_delivery_mediafile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="number_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.numbermodel"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.typepackage"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="stutus_delivery",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.statusdelivery",
            ),
        ),
        migrations.AlterField(
            model_name="numbermodel",
            name="name_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.modeltransport"
            ),
        ),
    ]
