# Generated by Django 5.2.3 on 2025-06-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_delivery_number_model_alter_delivery_package_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="stutus_delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.statusdelivery"
            ),
        ),
    ]
