# Generated by Django 5.2.3 on 2025-06-14 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_delivery_created_at_alter_delivery_stutus_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
