# Generated by Django 5.2.3 on 2025-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_delivery_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="mediafile",
            field=models.FileField(
                blank=True, null=True, upload_to="media", verbose_name="медиа файл"
            ),
        ),
    ]
