# Generated by Django 5.2.3 on 2025-06-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_delivery_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='technical_condition',
            field=models.CharField(choices=[('исправно', 'исправно'), ('неисправно', 'неисправно')], verbose_name='техническое состояние'),
        ),
    ]
