# Generated by Django 5.2.3 on 2025-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_delivery_technical_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='technical_condition',
            field=models.CharField(choices=[('properly', 'not working properly'), ('исправно', 'неисправно')], verbose_name='техническое состояние'),
        ),
    ]
